name: works_ease_ui
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  asset_picker:
#    path: /Users/liping/works_github/flutter_asset_picker
#      git:
#        url: git://github.com/cdworks/flutter_asset_picker.git
  #轮播图
  flutter_swiper: ^1.1.6

  #选择图片
  works_image_picker:
    path: /Users/liping/works_github/flutter_image_picker
#    git:
#      url: git://github.com/cdworks/flutter_image_picker.git

  #选择文件
  works_file_picker:
    path: /Users/liping/works_github/flutter_works_file_picker
#    git:
#      url: git://github.com/cdworks/flutter_works_file_picker.git

  #高德地图
  works_amap_map:
    path: /Users/liping/works_github/flutter_works_amap_map
#    git:
#      url: git://github.com/cdworks/flutter_works_amap_map.git

#  #键盘事件
#  flutter_keyboard_visibility: ^2.0.0

  #环信sdk
  im_flutter_sdk:
    path: /Users/liping/works_github/flutter_easemob_sdk
#    git:
#      url: git://github.com/cdworks/flutter_easemob_sdk.git

  #cache image
  cached_network_image: ^2.0.0

  #works公共接口
  works_common:
    #    git:
    #      url: git://github.com/cdworks/flutter_works_common.git
    path: /Users/liping/works_github/flutter_works_common

  #works工具类
  works_utils:
    path: /Users/liping/works_github/flutter_works_utils
#    git:
#      url: git://github.com/cdworks/flutter_works_utils.git

#  # 弹出菜单 ios
#  menu: ^0.1.4

  # 滑动删除等操作
  flutter_slidable: ^0.5.4

  #广播通知
  dart_notification_center: ^1.0.0+1

  #拼音
  lpinyin: ^1.0.8

  #A ScrollablePositionedList works much like the builder version of ListView except that the list can be scrolled or jumped to a specific item
  scrollable_positioned_list: ^0.1.4

  #本地通知
  flutter_local_notifications: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - easeuiImages/image_download_fail.png
    #chat
    - easeuiImages/chat/default_header.png
    - easeuiImages/chat/chat_bar_more_camera.png
    - easeuiImages/chat/chat_bar_more_face.png
    - easeuiImages/chat/chat_bar_more_file.png
    - easeuiImages/chat/chat_bar_more_keyboard.png
    - easeuiImages/chat/chat_bar_more_more.png
    - easeuiImages/chat/chat_bar_record.png
    - easeuiImages/chat/chat_bar_more_location.png
    - easeuiImages/chat/chat_bar_more_photo.png
    - easeuiImages/chat/voice_mic.png
    - easeuiImages/chat/voice_anim.gif
    - easeuiImages/chat/chat_receiver_bg.png
    - easeuiImages/chat/chat_sender_bg.png
    - easeuiImages/chat/chat_sender_audio_playing.png
    - easeuiImages/chat/chat_receiver_audio_playing.png
    - easeuiImages/chat/chat_sender_play.gif
    - easeuiImages/chat/chat_receiver_play.gif
    - easeuiImages/chat/file_type_pdf.png
    - easeuiImages/chat/file_type_text.png
    - easeuiImages/chat/file_type_excel.png
    - easeuiImages/chat/file_type_ppt.png
    - easeuiImages/chat/file_type_unkown.png
    - easeuiImages/chat/file_type_voice.png
    - easeuiImages/chat/file_type_word.png
    - easeuiImages/chat/file_type_zip.png
    - easeuiImages/chat/file_type_video.png
    - easeuiImages/chat/music_bg.png
    - easeuiImages/chat/chat_group_default.png
    - easeuiImages/chat/check_disable.png
    - easeuiImages/chat/check_slt.png
    - easeuiImages/chat/check_none.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
